# Generated by Django 5.1.7 on 2025-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
