# Generated by Django 5.1.7 on 2025-03-26 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payroll_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
    ]
